package vue;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import modele.Carte;
import modele.FluxDeClefs;

import javax.swing.*;
import java.io.File;

/**
 *
 * @author diallo
 */
public class Ihm extends javax.swing.JFrame {

    Carte carte ;
    FluxDeClefs fluxDeClefs;
    /**
     * Creates new form ihm
     */
    public Ihm() {
        initComponents();
        carte = new Carte();
        carte.initCarteAndMapBridge();
        fluxDeClefs = new FluxDeClefs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        PanelHaut = new javax.swing.JPanel();
        PanelCenter = new javax.swing.JPanel();
        pannelGaucheMilieu = new javax.swing.JPanel();
        PanelGauche1Milieu = new javax.swing.JPanel();
        bCrypterMessage1 = new javax.swing.JButton();
        bDecrypterMessage1 = new javax.swing.JButton();
        PanelGauche2Milieu = new javax.swing.JPanel();
        bCrypterFichier1 = new javax.swing.JButton();
        bDecrypterFichier1 = new javax.swing.JButton();
        PanelCenterMilieu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMessageCrypte1 = new javax.swing.JTextPane();
        AffichagePrincipale = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1jMessageCrypte2 = new javax.swing.JTextPane();
        pannelDroitMilieu = new javax.swing.JPanel();
        PanelDroit1Milieu = new javax.swing.JPanel();
        bCrypterMessage2 = new javax.swing.JButton();
        bDecrypterMessage2 = new javax.swing.JButton();
        PanelDroit2Milieu = new javax.swing.JPanel();
        bCrypterFichier2 = new javax.swing.JButton();
        bDecrypterFichier2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        javax.swing.GroupLayout PanelHautLayout = new javax.swing.GroupLayout(PanelHaut);
        PanelHaut.setLayout(PanelHautLayout);
        PanelHautLayout.setHorizontalGroup(
                PanelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1027, Short.MAX_VALUE)
        );
        PanelHautLayout.setVerticalGroup(
                PanelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 336, Short.MAX_VALUE)
        );

        getContentPane().add(PanelHaut);

        PanelCenter.setLayout(new java.awt.GridLayout(1, 3));

        pannelGaucheMilieu.setLayout(new java.awt.GridLayout(2, 0));

        PanelGauche1Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterMessage1.setText("Crypter Message");
        bCrypterMessage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterMessage1ActionPerformed(evt);
            }
        });
        PanelGauche1Milieu.add(bCrypterMessage1);

        bDecrypterMessage1.setText("Decrypter Message");
        bDecrypterMessage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterMessage1ActionPerformed(evt);
            }
        });
        PanelGauche1Milieu.add(bDecrypterMessage1);

        pannelGaucheMilieu.add(PanelGauche1Milieu);

        PanelGauche2Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterFichier1.setText("Crypter Fichier");
        bCrypterFichier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterFichier1ActionPerformed(evt);
            }
        });
        PanelGauche2Milieu.add(bCrypterFichier1);

        bDecrypterFichier1.setText("Decrypter Fichier");
        bDecrypterFichier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterFichier1ActionPerformed(evt);
            }
        });
        PanelGauche2Milieu.add(bDecrypterFichier1);

        pannelGaucheMilieu.add(PanelGauche2Milieu);

        PanelCenter.add(pannelGaucheMilieu);

        PanelCenterMilieu.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Message");
        jPanel2.add(jLabel2);

        jMessageCrypte1.setToolTipText("");
        jScrollPane2.setViewportView(jMessageCrypte1);

        jPanel2.add(jScrollPane2);

        PanelCenterMilieu.add(jPanel2);
        PanelCenterMilieu.add(AffichagePrincipale);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Decryptage");
        jLabel1.setAlignmentX(2.0F);
        jPanel1.add(jLabel1);

        jScrollPane3.setViewportView(jTextPane1jMessageCrypte2);

        jPanel1.add(jScrollPane3);

        PanelCenterMilieu.add(jPanel1);

        PanelCenter.add(PanelCenterMilieu);

        pannelDroitMilieu.setLayout(new java.awt.GridLayout(2, 0));

        PanelDroit1Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterMessage2.setText("Crypter Message");
        bCrypterMessage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterMessage2ActionPerformed(evt);
            }
        });
        PanelDroit1Milieu.add(bCrypterMessage2);

        bDecrypterMessage2.setText("Decrypter Message");
        bDecrypterMessage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterMessage2ActionPerformed(evt);
            }
        });
        PanelDroit1Milieu.add(bDecrypterMessage2);

        pannelDroitMilieu.add(PanelDroit1Milieu);

        PanelDroit2Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterFichier2.setText("Crypter Fichier");
        bCrypterFichier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterFichier2ActionPerformed(evt);
            }
        });
        PanelDroit2Milieu.add(bCrypterFichier2);

        bDecrypterFichier2.setText("Decrypter Fichier");
        bDecrypterFichier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterFichier2ActionPerformed(evt);
            }
        });
        PanelDroit2Milieu.add(bDecrypterFichier2);

        pannelDroitMilieu.add(PanelDroit2Milieu);

        PanelCenter.add(pannelDroitMilieu);

        getContentPane().add(PanelCenter);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>

    private void bCrypterMessage1ActionPerformed(java.awt.event.ActionEvent evt) {

        String message = jMessageCrypte1.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.crypterMessage(message,carte);
            AffichagePrincipale.setText(messageCrypte);
            jMessageCrypte1.setText("");
            bDecrypterMessage1.setEnabled(false);
            bDecrypterFichier1.setEnabled(false);
            bCrypterFichier1.setEnabled(false);
            bCrypterMessage2.setEnabled(false);
            bCrypterFichier2.setEnabled(false);
            bDecrypterFichier2.setEnabled(false);
        }

    }

    private void bCrypterMessage2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String message = jMessageCrypte1.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.crypterMessage(message,carte);
            AffichagePrincipale.setText(messageCrypte);
            jMessageCrypte1.setText("");
            bCrypterMessage1.setEnabled(false);
            bDecrypterMessage2.setEnabled(false);
            bDecrypterFichier2.setEnabled(false);
            bCrypterFichier1.setEnabled(false);
            bCrypterFichier2.setEnabled(false);
            bDecrypterFichier2.setEnabled(false);
            bDecrypterFichier1.setEnabled(false);
        }
    }

    private void bDecrypterMessage1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String message = jTextPane1jMessageCrypte2.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.decrypterMessage(message);
            AffichagePrincipale.setText(messageCrypte);
            jTextPane1jMessageCrypte2.setText("");

            bCrypterMessage1.setEnabled(true);
            bDecrypterMessage2.setEnabled(true);
            bDecrypterFichier2.setEnabled(true);
            bCrypterFichier1.setEnabled(true);
            bCrypterFichier2.setEnabled(true);
            bDecrypterFichier2.setEnabled(true);
            bDecrypterFichier1.setEnabled(true);
        }

    }

    private void bCrypterFichier1ActionPerformed(java.awt.event.ActionEvent evt) {
        //methode parcourir fichier du pc et appeler la methode crypter fichier
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            String messageCrypte=fluxDeClefs.crypterFichier(filename,carte);
            AffichagePrincipale.setText(messageCrypte);
            bCrypterMessage1.setEnabled(false);
            bDecrypterMessage1.setEnabled(false);
            bDecrypterFichier1.setEnabled(false);
            bCrypterMessage2.setEnabled(false);
            bCrypterFichier2.setEnabled(false);
            bDecrypterMessage2.setEnabled(false);
            jMessageCrypte1.setEnabled(false);
            jTextPane1jMessageCrypte2.setEnabled(false);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
        }


    }

    private void bDecrypterFichier2ActionPerformed(java.awt.event.ActionEvent evt) {
        //methode pour decrypter un fichier du pc et appeler la methode decrypter fichier
        try {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        String messageCrypte=fluxDeClefs.decrypteFichier(filename);
        AffichagePrincipale.setText(messageCrypte);

        bCrypterMessage1.setEnabled(true);
        bDecrypterMessage1.setEnabled(true);
        bDecrypterFichier1.setEnabled(true);
        bCrypterMessage2.setEnabled(true);
        bCrypterFichier2.setEnabled(true);
        bDecrypterMessage2.setEnabled(true);
        jMessageCrypte1.setEnabled(true);
        jTextPane1jMessageCrypte2.setEnabled(true);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
        }


    }

    private void bDecrypterFichier1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //methode pour decrypter un fichier du pc et appeler la methode decrypter fichier
        try {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        String messageCrypte=fluxDeClefs.decrypteFichier(filename);
        AffichagePrincipale.setText(messageCrypte);
        bCrypterMessage1.setEnabled(true);
        bDecrypterMessage1.setEnabled(true);
        bDecrypterFichier2.setEnabled(true);
        bCrypterMessage2.setEnabled(true);
        bDecrypterMessage2.setEnabled(true);
        bCrypterFichier1.setEnabled(true);
        jMessageCrypte1.setEnabled(true);
        jTextPane1jMessageCrypte2.setEnabled(true);
    }catch (NullPointerException e){
        JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
    }

    }

    private void bDecrypterMessage2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String message = jTextPane1jMessageCrypte2.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.decrypterMessage(message);
            jTextPane1jMessageCrypte2.setText("");
            AffichagePrincipale.setText(messageCrypte);
            bDecrypterMessage1.setEnabled(true);
            bDecrypterFichier1.setEnabled(true);
            bCrypterFichier1.setEnabled(true);
            bCrypterMessage2.setEnabled(true);
            bCrypterFichier2.setEnabled(true);
            bDecrypterFichier2.setEnabled(true);
        }

    }

    private void bCrypterFichier2ActionPerformed(java.awt.event.ActionEvent evt) {
        //methode parcourir fichier du pc et appeler la methode crypter fichier
        try {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        String messageCrypte=fluxDeClefs.crypterFichier(filename,carte);
        AffichagePrincipale.setText(messageCrypte);
        bCrypterMessage1.setEnabled(false);
        bDecrypterMessage1.setEnabled(false);
        bDecrypterFichier2.setEnabled(false);
        bCrypterMessage2.setEnabled(false);
        bDecrypterMessage2.setEnabled(false);
        bCrypterFichier1.setEnabled(false);
        jMessageCrypte1.setEnabled(false);
        jTextPane1jMessageCrypte2.setEnabled(false);
    }catch (NullPointerException e){
        JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ihm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField AffichagePrincipale;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelCenterMilieu;
    private javax.swing.JPanel PanelDroit1Milieu;
    private javax.swing.JPanel PanelDroit2Milieu;
    private javax.swing.JPanel PanelGauche1Milieu;
    private javax.swing.JPanel PanelGauche2Milieu;
    private javax.swing.JPanel PanelHaut;

    private javax.swing.JButton bCrypterFichier1;
    private javax.swing.JButton bCrypterFichier2;
    private javax.swing.JButton bCrypterMessage1;
    private javax.swing.JButton bCrypterMessage2;
    private javax.swing.JButton bDecrypterFichier1;
    private javax.swing.JButton bDecrypterFichier2;
    private javax.swing.JButton bDecrypterMessage1;
    private javax.swing.JButton bDecrypterMessage2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextPane jMessageCrypte1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1jMessageCrypte2;
    private javax.swing.JPanel pannelDroitMilieu;
    private javax.swing.JPanel pannelGaucheMilieu;
    // End of variables declaration
}
