package vue;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import modele.Carte;
import modele.FluxDeClefs;

import javax.swing.*;
import java.io.File;

/**
 *
 * @author diallo
 */
public class Ihm extends javax.swing.JFrame {

    Carte carte ;
    FluxDeClefs fluxDeClefs;
    /**
     * Creates new form ihm
     */
    public Ihm() {
        initComponents();
        carte = new Carte();
        carte.initCarteAndMapBridge();
        fluxDeClefs = new FluxDeClefs();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHaut = new javax.swing.JPanel();
        jboutonHaut = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        user1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        user2 = new javax.swing.JButton();
        PanelCenter = new javax.swing.JPanel();
        pannelGaucheMilieu = new javax.swing.JPanel();
        PanelGauche1Milieu = new javax.swing.JPanel();
        bCrypterMessage1 = new javax.swing.JButton();
        bDecrypterMessage1 = new javax.swing.JButton();
        PanelGauche2Milieu = new javax.swing.JPanel();
        bCrypterFichier1 = new javax.swing.JButton();
        bDecrypterFichier1 = new javax.swing.JButton();
        PanelCenterMilieu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMessageCrypte1 = new javax.swing.JTextPane();
        AffichagePrincipale = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1jMessageCrypte2 = new javax.swing.JTextPane();
        pannelDroitMilieu = new javax.swing.JPanel();
        PanelDroit1Milieu = new javax.swing.JPanel();
        bCrypterMessage2 = new javax.swing.JButton();
        bDecrypterMessage2 = new javax.swing.JButton();
        PanelDroit2Milieu = new javax.swing.JPanel();
        bCrypterFichier2 = new javax.swing.JButton();
        bDecrypterFichier2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        PanelHaut.setBackground(new java.awt.Color(11, 54, 29));
        PanelHaut.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 0, 1));
        PanelHaut.setLayout(new java.awt.GridLayout(2, 0));

        jboutonHaut.setBackground(new java.awt.Color(230, 230, 230));
        jboutonHaut.setIcon(new javax.swing.ImageIcon("./src/image/solitaireImg.png")); // NOI18N
        jboutonHaut.setBorderPainted(false);
        jboutonHaut.setContentAreaFilled(false);
        jboutonHaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboutonHautActionPerformed(evt);
            }
        });
        PanelHaut.add(jboutonHaut);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        user1.setBackground(new java.awt.Color(242, 242, 242));
        user1.setForeground(new java.awt.Color(242, 242, 242));
        user1.setIcon(new javax.swing.ImageIcon("./src/image/profile.png")); // NOI18N
        user1.setBorder(null);
        user1.setBorderPainted(false);
        user1.setContentAreaFilled(false);
        user1.setMaximumSize(new java.awt.Dimension(256, 800));
        user1.setMinimumSize(new java.awt.Dimension(256, 400));
        user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1ActionPerformed(evt);
            }
        });
        jPanel3.add(user1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4);

        user2.setBackground(new java.awt.Color(242, 242, 242));
        user2.setForeground(new java.awt.Color(242, 242, 242));
        user2.setIcon(new javax.swing.ImageIcon("./src/image/woman.png")); // NOI18N
        user2.setBorder(null);
        user2.setBorderPainted(false);
        user2.setContentAreaFilled(false);
        user2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user2ActionPerformed(evt);
            }
        });
        jPanel3.add(user2);

        PanelHaut.add(jPanel3);

        getContentPane().add(PanelHaut);

        PanelCenter.setLayout(new java.awt.GridLayout(1, 3));

        pannelGaucheMilieu.setLayout(new java.awt.GridLayout(2, 0));

        PanelGauche1Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterMessage1.setText("Crypter Message");
        bCrypterMessage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterMessage1ActionPerformed(evt);
            }
        });
        PanelGauche1Milieu.add(bCrypterMessage1);

        bDecrypterMessage1.setText("Decrypter Message");
        bDecrypterMessage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterMessage1ActionPerformed(evt);
            }
        });
        PanelGauche1Milieu.add(bDecrypterMessage1);

        pannelGaucheMilieu.add(PanelGauche1Milieu);

        PanelGauche2Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterFichier1.setText("Crypter Fichier");
        bCrypterFichier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterFichier1ActionPerformed(evt);
            }
        });
        PanelGauche2Milieu.add(bCrypterFichier1);

        bDecrypterFichier1.setText("Decrypter Fichier");
        bDecrypterFichier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterFichier1ActionPerformed(evt);
            }
        });
        PanelGauche2Milieu.add(bDecrypterFichier1);

        pannelGaucheMilieu.add(PanelGauche2Milieu);

        PanelCenter.add(pannelGaucheMilieu);

        PanelCenterMilieu.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Message");
        jPanel2.add(jLabel2);

        jMessageCrypte1.setToolTipText("");
        jScrollPane2.setViewportView(jMessageCrypte1);

        jPanel2.add(jScrollPane2);

        PanelCenterMilieu.add(jPanel2);
        PanelCenterMilieu.add(AffichagePrincipale);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Decryptage");
        jLabel1.setAlignmentX(2.0F);
        jPanel1.add(jLabel1);

        jScrollPane3.setViewportView(jTextPane1jMessageCrypte2);

        jPanel1.add(jScrollPane3);

        PanelCenterMilieu.add(jPanel1);

        PanelCenter.add(PanelCenterMilieu);

        pannelDroitMilieu.setLayout(new java.awt.GridLayout(2, 0));

        PanelDroit1Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterMessage2.setText("Crypter Message");
        bCrypterMessage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterMessage2ActionPerformed(evt);
            }
        });
        PanelDroit1Milieu.add(bCrypterMessage2);

        bDecrypterMessage2.setText("Decrypter Message");
        bDecrypterMessage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterMessage2ActionPerformed(evt);
            }
        });
        PanelDroit1Milieu.add(bDecrypterMessage2);

        pannelDroitMilieu.add(PanelDroit1Milieu);

        PanelDroit2Milieu.setLayout(new java.awt.GridLayout(2, 0));

        bCrypterFichier2.setText("Crypter Fichier");
        bCrypterFichier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrypterFichier2ActionPerformed(evt);
            }
        });
        PanelDroit2Milieu.add(bCrypterFichier2);

        bDecrypterFichier2.setText("Decrypter Fichier");
        bDecrypterFichier2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecrypterFichier2ActionPerformed(evt);
            }
        });
        PanelDroit2Milieu.add(bDecrypterFichier2);

        pannelDroitMilieu.add(PanelDroit2Milieu);

        PanelCenter.add(pannelDroitMilieu);

        getContentPane().add(PanelCenter);

        jMenu1.setText("Project Cryptographie");
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCrypterMessage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrypterMessage1ActionPerformed
        // TODO add your handling code here:
        String message = jMessageCrypte1.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.crypterMessage(message,carte);
            AffichagePrincipale.setText(messageCrypte);
            jMessageCrypte1.setText("");
            bDecrypterMessage1.setEnabled(false);
            bDecrypterFichier1.setEnabled(false);
            bCrypterFichier1.setEnabled(false);
            bCrypterMessage2.setEnabled(false);
            bCrypterFichier2.setEnabled(false);
            bDecrypterFichier2.setEnabled(false);
        }
    }//GEN-LAST:event_bCrypterMessage1ActionPerformed

    private void bCrypterMessage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrypterMessage2ActionPerformed
        // TODO add your handling code here:
        String message = jMessageCrypte1.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.crypterMessage(message,carte);
            AffichagePrincipale.setText(messageCrypte);
            jMessageCrypte1.setText("");
            bDecrypterFichier2.setEnabled(false);
            bDecrypterFichier1.setEnabled(false);
            bCrypterFichier1.setEnabled(false);
            bCrypterMessage1.setEnabled(false);
            bCrypterFichier2.setEnabled(false);
            bDecrypterFichier2.setEnabled(false);
            bDecrypterMessage2.setEnabled(false);

        }
    }

    private void bDecrypterMessage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDecrypterMessage1ActionPerformed
        // TODO add your handling code here:
        String message = jTextPane1jMessageCrypte2.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.decrypterMessage(message);
            AffichagePrincipale.setText(messageCrypte);
            jTextPane1jMessageCrypte2.setText("");

            bCrypterMessage1.setEnabled(true);
            bDecrypterMessage2.setEnabled(true);
            bDecrypterFichier2.setEnabled(true);
            bCrypterFichier1.setEnabled(true);
            bCrypterFichier2.setEnabled(true);
            bDecrypterFichier2.setEnabled(true);
            bDecrypterFichier1.setEnabled(true);
        }
    }//GEN-LAST:event_bDecrypterMessage1ActionPerformed

    private void bCrypterFichier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrypterFichier1ActionPerformed
        // TODO add your handling code here:
        //methode parcourir fichier du pc et appeler la methode crypter fichier
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            String messageCrypte=fluxDeClefs.crypterFichier(filename,carte);
            AffichagePrincipale.setText(messageCrypte);
            bCrypterMessage1.setEnabled(false);
            bDecrypterMessage1.setEnabled(false);
            bDecrypterFichier1.setEnabled(false);
            bCrypterMessage2.setEnabled(false);
            bCrypterFichier2.setEnabled(false);
            bDecrypterMessage2.setEnabled(false);
            jMessageCrypte1.setEnabled(false);
            jTextPane1jMessageCrypte2.setEnabled(false);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void bDecrypterFichier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDecrypterFichier2ActionPerformed
        // TODO add your handling code here:
        //methode pour decrypter un fichier du pc et appeler la methode decrypter fichier
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            String messageCrypte=fluxDeClefs.decrypteFichier(filename);
            AffichagePrincipale.setText(messageCrypte);

            bCrypterMessage1.setEnabled(true);
            bDecrypterMessage1.setEnabled(true);
            bDecrypterFichier1.setEnabled(true);
            bCrypterMessage2.setEnabled(true);
            bCrypterFichier2.setEnabled(true);
            bDecrypterMessage2.setEnabled(true);
            jMessageCrypte1.setEnabled(true);
            jTextPane1jMessageCrypte2.setEnabled(true);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bDecrypterFichier2ActionPerformed

    private void bDecrypterFichier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDecrypterFichier1ActionPerformed
        // TODO add your handling code here:
        //methode pour decrypter un fichier du pc et appeler la methode decrypter fichier
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            String messageCrypte=fluxDeClefs.decrypteFichier(filename);
            AffichagePrincipale.setText(messageCrypte);
            bCrypterMessage1.setEnabled(true);
            bDecrypterMessage1.setEnabled(true);
            bDecrypterFichier2.setEnabled(true);
            bCrypterMessage2.setEnabled(true);
            bDecrypterMessage2.setEnabled(true);
            bCrypterFichier1.setEnabled(true);
            jMessageCrypte1.setEnabled(true);
            jTextPane1jMessageCrypte2.setEnabled(true);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bDecrypterFichier1ActionPerformed

    private void bDecrypterMessage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDecrypterMessage2ActionPerformed
        // TODO add your handling code here:
        String message = jTextPane1jMessageCrypte2.getText();
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un message", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else{

            String messageCrypte=fluxDeClefs.decrypterMessage(message);
            jTextPane1jMessageCrypte2.setText("");
            AffichagePrincipale.setText(messageCrypte);
            bDecrypterMessage1.setEnabled(true);
            bDecrypterFichier1.setEnabled(true);
            bCrypterFichier1.setEnabled(true);
            bCrypterMessage2.setEnabled(true);
            bCrypterFichier2.setEnabled(true);
            bDecrypterFichier2.setEnabled(true);
        }
    }//GEN-LAST:event_bDecrypterMessage2ActionPerformed

    private void bCrypterFichier2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrypterFichier2ActionPerformed
        // TODO add your handling code here:
        //methode parcourir fichier du pc et appeler la methode crypter fichier
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            String messageCrypte=fluxDeClefs.crypterFichier(filename,carte);
            AffichagePrincipale.setText(messageCrypte);
            bCrypterMessage1.setEnabled(false);
            bDecrypterMessage1.setEnabled(false);
            bDecrypterFichier2.setEnabled(false);
            bCrypterMessage2.setEnabled(false);
            bDecrypterMessage2.setEnabled(false);
            bCrypterFichier1.setEnabled(false);
            jMessageCrypte1.setEnabled(false);
            jTextPane1jMessageCrypte2.setEnabled(false);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null, "Veuillez entrer un fichier", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bCrypterFichier2ActionPerformed

    private void jboutonHautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboutonHautActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jboutonHautActionPerformed

    private void user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1ActionPerformed

    private void user2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ihm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ihm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AffichagePrincipale;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelCenterMilieu;
    private javax.swing.JPanel PanelDroit1Milieu;
    private javax.swing.JPanel PanelDroit2Milieu;
    private javax.swing.JPanel PanelGauche1Milieu;
    private javax.swing.JPanel PanelGauche2Milieu;
    private javax.swing.JPanel PanelHaut;
    private javax.swing.JButton bCrypterFichier1;
    private javax.swing.JButton bCrypterFichier2;
    private javax.swing.JButton bCrypterMessage1;
    private javax.swing.JButton bCrypterMessage2;
    private javax.swing.JButton bDecrypterFichier1;
    private javax.swing.JButton bDecrypterFichier2;
    private javax.swing.JButton bDecrypterMessage1;
    private javax.swing.JButton bDecrypterMessage2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextPane jMessageCrypte1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1jMessageCrypte2;
    private javax.swing.JButton jboutonHaut;
    private javax.swing.JPanel pannelDroitMilieu;
    private javax.swing.JPanel pannelGaucheMilieu;
    private javax.swing.JButton user1;
    private javax.swing.JButton user2;
    // End of variables declaration//GEN-END:variables
}
